hash-format = "sha256"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1e0ba1e744212f481d857e2c864104eb8853a825f6557874b739763e208f7e59"

[[files]]
file = "config/yosbr/config/servercore.toml"
hash = "4f5cd08148f87464a0f5e471787fd609a6546b653845954598e5a240b938a32d"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "c37edec3875da8e561eb60bb7a18dcdce128cc41cfe26261c65a8e942f65d58f"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "5afe4e900b83aa83109d0c845df28e9695d8e3639518b0f08169a547f0e3682b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "39a6a39433b1b104bfafafcd60a8171f866daa2ebefffd64df822d0e69288e3a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "8bd4f3e61a962c0b730a9a9b5ce875b571ae7e39d350ad52b17f9fab467a3784"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "5a6df3930d69602402cd13bf860195ac44680e2d4556e8d1254ae730fcb4b0f9"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "182161aa8e4b730555dd9984efb7be8cfd3debbaf1d4cc60e0b3241402e6f2bc"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "218f67d6bcaae849582618cd3e5eb1d4cac0fd6045115f64340620300e160c11"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "dbbeb7a8f32fdbe0d5e44a8c7671ed2297ee8d12d4610500ac54742e70b4fb53"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "40f1effd2c65b6c6f9a1b5dfd0903c87df02b23da6b57f389f61f361ef86d425"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true
