name = "Adrenaserver"
author = "getchoo"
version = "1.5.0+1.20.4.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3ab2a19927a18994a8b075c7b8de8fb8758a66674e046f78020712623fc33cd"

[versions]
minecraft = "1.20.4"
quilt = "0.25.0"
